---
- name: Update root password for MariaDB (if configured)
  mysql_user:
    name: root
    host: localhost
    password: "{{ mariadb_root_password }}"
  when: (mariadb_packages_installed) or mariadb_root_password_update

- name: Copy .my.cnf with root crendetial
  template:
    src: my-root.cnf.j2
    dest: "{{ mariadb_root_home }}/.my.cnf"
    mode: 0600

# - name: Removes all anonymous user accounts
#  mysql_user:
#    name: ''
#    host_all: true
#    state: absent
#    login_user: root
#    login_password: "{{ mariadb_root_password }}"

# - name: Remove test database
#  mysql_db:
#    name: "test"
#    state: "absent"
#    login_user: root
#    login_password: "{{ mariadb_root_password }}"
