---

- name: Update root password for MariaDB (Debian 10)
  command: >
    mysql -u root -NBe
    'ALTER USER "{{ mariadb_root_username }}"@"localhost"
    IDENTIFIED BY "{{ mariadb_root_password }}";'
  when: >
    ((mariadb_packages_installed) or mariadb_root_password_update) and
    (ansible_distribution == 'Debian' and ansible_distribution_major_version == '10')

- name: Update root password for MariaDB (Debian 9)
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: localhost
    state: present
  when: >
    ((mariadb_packages_installed) or mariadb_root_password_update) and
    (ansible_distribution == 'Debian' and ansible_distribution_major_version == '9')

- name: Copy .my.cnf with root crendetial
  template:
    src: my-root.cnf.j2
    dest: "{{ mariadb_root_home }}/.my.cnf"
    mode: 0600

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: true
    state: absent

- name: Remove test database
  mysql_db:
    name: "test"
    state: "absent"
