---
- name: Update apt cache
  apt:
    update_cache: true

- name: Install Pip
  package:
    name: python-pip
    state: present

- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: present

- name: Install Python Librairies for MariaDB
  package:
    name: "{{ mariadb_python_librairies }}"
    state: present

- name: Install MariaDB Packages
  package:
    name: "{{ mariadb_packages }}"
    state: present
  register: mariadb_packages_installed
  notify: Reload systemd

- name: Flush Handlers
  meta: flush_handlers
