---
- name: Converge
  hosts: all
  roles:
    - role: supertarto.mariadb
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false
  vars:
    mariadb_use_dump_script: true

    mariadb_databases:
      - name: database1
        collation: utf8_general_ci
        encoding: utf8

    mariadb_users:
      - name: username
        host: localhost
        password: sqlpassword
        priv: "database1.*:SELECT,UPDATE"

      - name: "{{ mariadb_dump_user }}"
        host: localhost
        password: "{{ mariadb_dump_pass }}"
        priv: "*.*:SELECT,LOCK TABLES"

    mariadb_dump_user: "dumpuser"
    mariadb_dump_pass: "Dumppassword"

    mariadb_port: "3306"

  post_tasks:
    - name: Make sure we can connect to MySQL via Unix socket.
      command: "mysql -u root -proot -e 'show databases;'"
      changed_when: false

    - name: Make sure we can connect to MySQL via TCP.
      command: "mysql -u root -proot -h 127.0.0.1 -e 'show databases;'"
      changed_when: false
